import os
import logging
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.cluster.hierarchy import dendrogram
import numpy as np
import pandas as pd

logger = logging.getLogger(__name__)

def generate_dendrogram(linkage_matrix: np.ndarray, labels: list, title: str, export_path: str) -> None:
    """
    Render and export a hierarchical clustering dendrogram.
    
    Args:
        linkage_matrix (np.ndarray): The Z matrix generated by the clustering algorithm.
        labels (list): Leaf labels for the dendrogram.
        title (str): Title of the plot.
        export_path (str): Absolute or relative path to save the artifact.
    """
    plt.figure(figsize=(14, 8))
    plt.title(title, fontsize=15, pad=20)
    plt.xlabel("Sample / Feature Index", fontsize=12)
    plt.ylabel("Linkage Distance", fontsize=12)
    
    dendrogram(
        linkage_matrix,
        labels=labels,
        leaf_rotation=90.,
        leaf_font_size=9.,
        color_threshold=None
    )
    
    plt.tight_layout()
    plt.savefig(export_path, dpi=300)
    plt.close()
    logger.info(f"Dendrogram exported successfully to: {export_path}")

def generate_biclustering_heatmap(data: pd.DataFrame, row_linkage: np.ndarray, 
                                  col_linkage: np.ndarray, row_labels: list, 
                                  col_labels: list, title: str, export_path: str) -> None:
    """
    Render and export a biclustering heatmap illustrating both row and column hierarchies.
    
    Args:
        data (pd.DataFrame): Normalized expression matrix.
        row_linkage (np.ndarray): Linkage matrix for genes (features).
        col_linkage (np.ndarray): Linkage matrix for patients (samples).
        row_labels (list): Gene identifiers.
        col_labels (list): Patient identifiers.
        title (str): Plot title.
        export_path (str): Export destination path.
    """
    cluster_grid = sns.clustermap(
        data,
        row_linkage=row_linkage,
        col_linkage=col_linkage,
        yticklabels=row_labels,
        xticklabels=col_labels,
        cmap='coolwarm',
        figsize=(12, 10),
        dendrogram_ratio=(0.2, 0.2),
        cbar_pos=(0.02, 0.8, 0.05, 0.18)
    )
    
    cluster_grid.fig.suptitle(title, fontsize=16, y=1.05)
    plt.savefig(export_path, dpi=300, bbox_inches='tight')
    plt.close()
    logger.info(f"Biclustering heatmap exported successfully to: {export_path}")